-- ╔════════════════════════════════════════════════════════════════╗
-- ║  AUTO-GENERATED — do not edit by hand.                        ║
-- ║  Re-generate: ./scripts/generate-compose.sh                   ║
-- ╚════════════════════════════════════════════════════════════════╝

CREATE DATABASE IF NOT EXISTS `wp_81_61`;
CREATE DATABASE IF NOT EXISTS `wp_81_62`;
CREATE DATABASE IF NOT EXISTS `wp_81_63`;
CREATE DATABASE IF NOT EXISTS `wp_81_64`;
CREATE DATABASE IF NOT EXISTS `wp_81_65`;
CREATE DATABASE IF NOT EXISTS `wp_81_66`;
CREATE DATABASE IF NOT EXISTS `wp_81_67`;
CREATE DATABASE IF NOT EXISTS `wp_81_68`;
CREATE DATABASE IF NOT EXISTS `wp_81_69`;
CREATE DATABASE IF NOT EXISTS `wp_82_61`;
CREATE DATABASE IF NOT EXISTS `wp_82_62`;
CREATE DATABASE IF NOT EXISTS `wp_82_63`;
CREATE DATABASE IF NOT EXISTS `wp_82_64`;
CREATE DATABASE IF NOT EXISTS `wp_82_65`;
CREATE DATABASE IF NOT EXISTS `wp_82_66`;
CREATE DATABASE IF NOT EXISTS `wp_82_67`;
CREATE DATABASE IF NOT EXISTS `wp_82_68`;
CREATE DATABASE IF NOT EXISTS `wp_82_69`;
CREATE DATABASE IF NOT EXISTS `wp_82_70`;
CREATE DATABASE IF NOT EXISTS `wp_83_64`;
CREATE DATABASE IF NOT EXISTS `wp_83_65`;
CREATE DATABASE IF NOT EXISTS `wp_83_66`;
CREATE DATABASE IF NOT EXISTS `wp_83_67`;
CREATE DATABASE IF NOT EXISTS `wp_83_68`;
CREATE DATABASE IF NOT EXISTS `wp_83_69`;
CREATE DATABASE IF NOT EXISTS `wp_83_70`;
CREATE DATABASE IF NOT EXISTS `wp_84_67`;
CREATE DATABASE IF NOT EXISTS `wp_84_68`;
CREATE DATABASE IF NOT EXISTS `wp_84_69`;
CREATE DATABASE IF NOT EXISTS `wp_84_70`;
CREATE DATABASE IF NOT EXISTS `wp_85_68`;
CREATE DATABASE IF NOT EXISTS `wp_85_69`;
CREATE DATABASE IF NOT EXISTS `wp_85_70`;

-- Grant the wordpress user access to all wp_* databases
GRANT ALL PRIVILEGES ON `wp_%`.* TO 'wordpress'@'%';
FLUSH PRIVILEGES;
